---
{{- if .Values.configs.lmcache.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "models.fullname" . }}-lmcache-config
  namespace: {{ .Values.namespace }}
data:
  lmcache.yaml: |
    internal_api_server_enabled: True
    internal_api_server_port_start: 6999

    chunk_size: {{ .Values.configs.lmcache.chunk_size }}
    save_unfull_chunk: {{ .Values.configs.lmcache.save_unfull_chunk }}
    min_retrieve_tokens: 0

    {{- if eq .Values.configs.lmcache.cpu.enable true }}
    local_cpu: True
    max_local_cpu_size: {{ .Values.configs.lmcache.cpu.max_size }}
    {{- else }}
    local_cpu: False
    max_local_cpu_size: 5.0
    {{- end }}

{{- if eq .Values.configs.lmcache.cache_type "local_storage" }}
    local_disk: "file:///mnt/localstorage/cache"
    max_local_disk_size: 10.0
{{- end }}

{{- if eq .Values.configs.lmcache.cache_type "gds" }}
    gds_path: "/mnt/gds/cache"
    cufile_buffer_size: 8192
{{- end }}

{{- if eq .Values.configs.lmcache.cache_type "nixl_posix" }}
    nixl_buffer_size: 1073741824 # 1GB
    nixl_buffer_device: cpu
    extra_config:
      enable_nixl_storage: true
      nixl_backend: POSIX
      nixl_pool_size: 64
      nixl_path: /mnt/nixl/cache/posix
      use_direct_io: true
      nixl_backend_params:
        use_uring: "true"
{{- end }}

{{- if eq .Values.configs.lmcache.cache_type "nixl_gds" }}
    nixl_buffer_size: 1073741824 # 1GB
    nixl_buffer_device: cuda
    extra_config:
      enable_nixl_storage: true
      nixl_backend: GDS
      nixl_pool_size: 64
      nixl_path: /mnt/nixl/cache/gds
      use_direct_io: true
      nixl_backend_params:
        cufile_buffer_size: 8192
        use_compat_mode: "false"
{{- end }}

{{- end }}
