---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "models.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: vllm
    model: {{ .Values.configs.name }}
    name: {{ include "models.fullname" . }}
spec:
  tolerations: # must have this to schedule on GPU nodes
  - key: "level"
    operator: "Equal"
    value: "important"
    effect: "NoSchedule"

  nodeSelector:
    {{- if eq .Values.gpu.type "a5000" }}
    kubernetes.io/hostname: sunyibm1.fsl.cs.sunysb.edu
    {{- else if eq .Values.gpu.type "q6000" }}
    kubernetes.io/hostname: sunyibm2.fsl.cs.sunysb.edu
    {{- else }}
    {{ fail "Invalid gpu type value. Use 'a5000' or 'q6000'." }}
    {{- end }}

  restartPolicy: Never

  {{- if .Values.bedrock.enable }}
  hostPID: true
  {{- end }}

  volumes:
  - name: shm
    emptyDir:
      medium: Memory
  - name: chat-template
    configMap:
      name: chat-template
  - name: cache-volume
    {{- if eq .Values.storage.type "local" }}
    hostPath:
      {{- if or (hasPrefix "deepseek" .Values.configs.name) (hasPrefix "ibm" .Values.configs.name) }}
      path: /mnt/data/vllm-cache
      {{- else }}
      path: /mnt/vllm
      {{- end }}
      type: DirectoryOrCreate
    {{- else if eq .Values.storage.type "gpfs" }}
    persistentVolumeClaim:
      claimName: vllm-pvc
    {{- else }}
    {{ fail "Invalid storage type value. Use 'local' or 'gpfs'." }}
    {{- end }}
  {{- if .Values.configs.lmcache.enable }}
  - name: lmcache-config
    configMap:
      name: {{ include "models.fullname" . }}-lmcache-config
  - name: lmcache-cpu-config
    configMap:
      name: {{ include "models.fullname" . }}-lmcache-cpu-config
  - name: lmcache-storage
    hostPath:
      {{- if eq .Values.configs.lmcache.cache_type "local_storage" }}
      path: /mnt/data/lmcache/localstorage/cache
      {{- else if eq .Values.configs.lmcache.cache_type "gds" }}
      path: /mnt/data/lmcache/gds/cache
      {{- else if eq .Values.configs.lmcache.cache_type "nixl_posix" }}
      path: /mnt/data/lmcache/nixl/cache/posix
      {{- else if eq .Values.configs.lmcache.cache_type "nixl_gds" }}
      path: /mnt/data/lmcache/nixl/cache/gds
      {{- else }}
      {{ fail "Invalid lmcache cache_type." }}
      {{- end }}
      type: DirectoryOrCreate
  {{- end }}
  {{- if .Values.bedrock.enable }}
  - name: sys
    hostPath:
      path: /sys
      type: Directory
  - name: modules
    hostPath:
      path: /lib/modules
      type: Directory
  - name: bedrock-logs
    hostPath:
      path: {{ printf "/mnt/data/bedrock/logs/%s" .Values.configs.name }}
      type: DirectoryOrCreate
  - name: containerd-socket
    hostPath:
      path: /run/containerd/containerd.sock
      type: Socket
  {{- end }}

  containers:
  {{- if .Values.bedrock.enable }}
  - name: bedrock-sidecar
    image: {{ .Values.bedrock.image }}
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: false
      capabilities:
        add:
          - SYS_ADMIN
          - SYS_RESOURCE
          - SYS_PTRACE
          - NET_ADMIN
          - PERFMON
          - BPF
    volumeMounts:
    - name: sys
      mountPath: /sys
    - name: modules
      mountPath: /lib/modules
    - name: bedrock-logs
      mountPath: /logs
    - name: containerd-socket
      mountPath: /run/containerd/containerd.sock
      readOnly: true
    env:
    - name: CONTAINER_RUNTIME_ENDPOINT
      value: unix:///run/containerd/containerd.sock
    command: ["bdtrace"]
    args:
      - --out
      - /logs
      - --kubernetes__namespace
      - {{ .Values.namespace | quote }}
      - --kubernetes__pod
      - {{ include "models.fullname" . | quote }}
      - --kubernetes__container
      - vllm-container
      - --rotate
      - --rotate_size
      - 200Mb
      - --disable_memory_map
  {{- end }}
  - name: vllm-container
    image: vllm/vllm-openai:{{ .Values.image.tag }}
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    - >
      {{- if .Values.bedrock.enable }}
      sleep 30 &&
      {{- end }}
      vllm serve {{ .Values.configs.model }} --host 0.0.0.0 --port 8000 --enable-prefix-caching --seed 0 --chat-template /templates/chat_template.jinja --gpu-memory-utilization {{ .Values.configs.gpu_memory_utilization }} --tensor-parallel-size {{ .Values.gpu.count }} {{- if .Values.configs.max_model_len }} --max-model-len {{ .Values.configs.max_model_len }} {{- end }} {{- if .Values.configs.max_num_seqs }} --max-num-seqs {{ .Values.configs.max_num_seqs }} {{- end }} {{- if .Values.configs.lmcache.enable }} --kv-transfer-config '{{ .Values.configs.kv_transfer_config }}' {{- end }}

    env:
    - name: LD_PRELOAD
      value: "/lib/x86_64-linux-gnu/libcuda.so.1 /lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1"
    - name: HF_TOKEN
      valueFrom:
        secretKeyRef:
          name: hf-token-secret
          key: token
    - name: TZ
      value: UTC
    {{- if .Values.configs.lmcache.enable }}
    - name: LMCACHE_USE_EXPERIMENTAL
      value: "True"
    # - name: LMCACHE_CONFIG_FILE
    #   value: "/etc/lmcache/lmcache.yaml"
    {{- end }}

    ports:
    - containerPort: 8000
      name: vllm-api
    - containerPort: 7000
      name: lmcache-api
    - containerPort: 9000
      name: lmcache-cpu-api

    resources:
      limits:
        cpu: {{ .Values.resources.cpu_limit | default "10" }}
        memory: {{ .Values.resources.memory_limit | default "25G" }}
        nvidia.com/gpu: {{ .Values.gpu.count | default 1 }}
      requests:
        cpu: {{ .Values.resources.cpu_request | default "5" }}
        memory: {{ .Values.resources.memory_request | default "12G" }}
        nvidia.com/gpu: {{ .Values.gpu.count | default 1 }}

    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /root/.cache/huggingface
      name: cache-volume
    - mountPath: /templates
      name: chat-template
      readOnly: true
    {{- if .Values.configs.lmcache.enable }}
    - name: lmcache-config
      mountPath: /etc/lmcache/lmcache
      readOnly: true
    - name: lmcache-cpu-config
      mountPath: /etc/lmcache/cpu
      readOnly: true
    - name: lmcache-storage
      {{- if eq .Values.configs.lmcache.cache_type "local_storage" }}
      mountPath: /mnt/localstorage/cache
      {{- else if eq .Values.configs.lmcache.cache_type "gds" }}
      mountPath: /mnt/gds/cache
      {{- else if eq .Values.configs.lmcache.cache_type "nixl_posix" }}
      mountPath: /mnt/nixl/cache/posix
      {{- else if eq .Values.configs.lmcache.cache_type "nixl_gds" }}
      mountPath: /mnt/nixl/cache/gds
      {{- end }}
    {{- end }}

    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: {{ .Values.liveprobe.initdelay | default 120 }}
      periodSeconds: {{ .Values.liveprobe.period | default 60 }}

    readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: {{ .Values.readyprobe.initdelay | default 120 }}
      periodSeconds: {{ .Values.readyprobe.period | default 60 }}
