---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.configs.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: vllm
    model: {{ .Values.configs.name }}
spec:
  tolerations: # must have this to schedule on GPU nodes
  - key: "level"
    operator: "Equal"
    value: "important"
    effect: "NoSchedule"

  nodeSelector:
    {{- if eq .Values.gpu.type "a5000" }}
    kubernetes.io/hostname: sunyibm1.fsl.cs.sunysb.edu
    {{- else if eq .Values.gpu.type "q6000" }}
    kubernetes.io/hostname: sunyibm2.fsl.cs.sunysb.edu
    {{- else }}
    {{ fail "Invalid gpu type value. Use 'a5000' or 'q6000'." }}
    {{- end }}

  restartPolicy: Never

  volumes:
  - name: shm
    emptyDir:
      medium: Memory
  - name: cache-volume
    {{- if eq .Values.storage.type "local" }}
    hostPath:
      path: /mnt/vllm
      type: DirectoryOrCreate
    {{- else if eq .Values.storage.type "gpfs" }}
    persistentVolumeClaim:
      claimName: vllm-pvc
    {{- else }}
    {{ fail "Invalid storage type value. Use 'local' or 'gpfs'." }}
    {{- end }}
  {{- if .Values.configs.lmcache.enable }}
  - name: lmcache-config
    configMap:
      name: {{ .Values.configs.name }}-lmcache-config
  - name: lmcache-storage
    hostPath:
      {{- if eq .Values.configs.lmcache.cache_type "local_storage" }}
      path: /mnt/lmcache/localstorage/cache
      {{- else if eq .Values.configs.lmcache.cache_type "gds" }}
      path: /mnt/lmcache/gds/cache
      {{- else if eq .Values.configs.lmcache.cache_type "nixl_posix" }}
      path: /mnt/lmcache/nixl/cache/posix
      {{- else if eq .Values.configs.lmcache.cache_type "nixl_gds" }}
      path: /mnt/lmcache/nixl/cache/gds
      {{- else }}
      {{ fail "Invalid lmcache cache_type." }}
      {{- end }}
      type: Directory
  {{- end }}

  containers:
  - name: vllm-container
    image: vllm/vllm-openai:v0.15.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args:
    {{- toYaml .Values.configs.serve | nindent 6 }}

    env:
    - name: HF_TOKEN
      valueFrom:
        secretKeyRef:
          name: hf-token-secret
          key: token
    - name: TZ
      value: UTC
    {{- if .Values.configs.lmcache.enable }}
    - name: LMCACHE_USE_EXPERIMENTAL
      value: "True"
    - name: LMCACHE_CONFIG_FILE
      value: "/etc/lmcache/lmcache.yaml"
    {{- end }}

    ports:
    - containerPort: 8000

    resources:
      limits:
        cpu: "10"
        memory: 25G
        nvidia.com/gpu: {{ .Values.gpu.count | default 1 }}
      requests:
        cpu: "5"
        memory: 12G
        nvidia.com/gpu: {{ .Values.gpu.count | default 1 }}

    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /root/.cache/huggingface
      name: cache-volume
    {{- if .Values.configs.lmcache.enable }}
    - name: lmcache-config
      mountPath: /etc/lmcache
      readOnly: true
    - name: lmcache-storage
      {{- if eq .Values.configs.lmcache.cache_type "local_storage" }}
      mountPath: /mnt/localstorage/cache
      {{- else if eq .Values.configs.lmcache.cache_type "gds" }}
      mountPath: /mnt/gds/cache
      {{- else if eq .Values.configs.lmcache.cache_type "nixl_posix" }}
      mountPath: /mnt/nixl/cache/posix
      {{- else if eq .Values.configs.lmcache.cache_type "nixl_gds" }}
      mountPath: /mnt/nixl/cache/gds
      {{- end }}
    {{- end }}

    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: {{ .Values.liveprobe.initdelay | default 120 }}
      periodSeconds: {{ .Values.liveprobe.period | default 60 }}

    readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: {{ .Values.readyprobe.initdelay | default 120 }}
      periodSeconds: {{ .Values.readyprobe.period | default 60 }}
