{
 "title": "Autopilot Health Check Dashboard",
 "description": "Autopilot GPU health checking dashboard.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(autopilot_health_checks,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ping",
   "type": "timeseries",
   "description": "Network reachability check",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "autopilot_health_checks{health=\"ping\", node=~\"${node}\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "DCGM",
   "type": "timeseries",
   "description": "GPU Diagnostics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "autopilot_health_checks{health=\"dcgm\", node=~\"${node}\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Remapped",
   "type": "timeseries",
   "description": "GPU memory check",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "autopilot_health_checks{health=\"remapped\", node=~\"${node}\"}",
     "legendFormat": "{{node}}-{{deviceid}}"
    }
   ]
  },
  {
   "title": "Power Slowdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "autopilot_health_checks{health=\"power-slowdown\", node=~\"${node}\"}",
     "legendFormat": "{{node}}-{{deviceid}}"
    }
   ]
  },
  {
   "title": "PCIe Bandwidth Check",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "autopilot_health_checks{health=\"pciebw\", node=~\"${node}\"}",
     "legendFormat": "{{node}}-{{deviceid}}"
    }
   ]
  }
 ]
}