{
 "title": "vLLM Monitoring",
 "description": "A collection of all app and platform metrics for vLLM instances.",
 "tags": [ "vllm" ],
 "time": { "from": "2026-04-13T17:18:35.310Z", "to": "2026-04-13T17:35:59.868Z" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "direction": "forward",
       "expr": "{namespace=~\"$namespace\", pod=~\"$pod\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage Rate",
     "type": "timeseries",
     "description": "How much CPU time (in seconds per second) each container is using, summed over all cores, as a rate.\n\ne.g., 2.0 using two cores fully",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster\", container!=\"\"}) by (container)",
       "legendFormat": "container : {{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Memory actively used (excludes cache that can be reclaimed) in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}) by (container)",
       "legendFormat": "container : {{container}}"
      },
      {
       "expr": "sum(\r\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\"}\r\n) by (pod)",
       "legendFormat": "{{pod}} : requests"
      },
      {
       "expr": "sum(\r\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\"}\r\n) by (pod)",
       "legendFormat": "{{pod}} : limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Throughput",
     "type": "timeseries",
     "description": "Sum rate of cumulative count of bytes received/transmitted",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} : ingress"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} : egress"
      }
     ]
    },
    {
     "title": "Packet Rate",
     "type": "timeseries",
     "description": "Cumulative count of bytes received/transmitted.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} : ingress"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} : egress"
      }
     ]
    }
   ]
  },
  {
   "title": "File System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "description": "Number of open file descriptors for the container.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "container_file_descriptors{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk R/W Rate",
     "type": "timeseries",
     "description": "Cumulative count of bytes read/write.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(namespace, pod) (rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}} : FS Read"
      },
      {
       "expr": "sum by(namespace, pod) (rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}} : FS Write"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "timeseries",
     "description": "Ceil of rated sum of cumulative count of bytes read/write.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "{{pod}} : read"
      },
      {
       "expr": "ceil(sum by(pod) (rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "{{pod}} : write"
      }
     ]
    },
    {
     "title": "I/O Throughput",
     "type": "timeseries",
     "description": "Rate of cumulative count of bytes read/write.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}} : read"
      },
      {
       "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}} : write"
      }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "timeseries",
     "description": "Total memory used (includes cache).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 376 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Mapped Files",
     "type": "timeseries",
     "description": "Mapped file memory (shared libs, mmap files) in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 376 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_mapped_file{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Swap Memory",
     "type": "timeseries",
     "description": "Swap memory used in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 699 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_swap{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Page Cache Memory",
     "type": "timeseries",
     "description": "Page cache memory used by container.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 699 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_cache{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Peak Memory Usage",
     "type": "timeseries",
     "description": "Peak memory usage observed in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 707 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_max_usage_bytes{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Resident Set Size",
     "type": "timeseries",
     "description": "Resident Set Size (anonymous + file-backed memory in RAM) in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 707 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OOM Attempts",
     "type": "timeseries",
     "description": "Number of memory allocation failures (OOM attempts).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 715 },
     "targets": [
      {
       "expr": "container_memory_failcnt{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OOM Events",
     "type": "timeseries",
     "description": "Number of OOM events.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 715 },
     "targets": [
      {
       "expr": "container_oom_events_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 377 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_TEMP{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"}",
       "legendFormat": "Pod: {{exported_pod}} - Node:{{Hostname}} - GPU:{{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Power Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 377 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_POWER_USAGE{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"}",
       "legendFormat": "Pod: {{exported_pod}} - Node:{{Hostname}} - GPU:{{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 700 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_UTIL{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"}",
       "legendFormat": "Pod: {{exported_pod}} - Node:{{Hostname}} - GPU:{{gpu}}"
      }
     ]
    },
    {
     "title": "Tensor Core Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 700 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"}",
       "legendFormat": "Pod: {{exported_pod}} - Node:{{Hostname}} - GPU:{{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Active Utilization",
     "type": "timeseries",
     "description": "These all start with DCGM_FI_PROF_* Ratio of time the graphics engine is active. The graphics engine is active if a graphics/compute context is bound and the graphics pipe or compute pipe is busy.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 708 },
     "targets": [
      {
       "expr": "DCGM_FI_PROF_GR_ENGINE_ACTIVE{exported_namespace=\"$namespace\", exported_pod=\"$pod\"}",
       "legendFormat": "Pod: {{exported_pod}} - Node:{{Hostname}} - GPU:{{gpu}}"
      }
     ]
    },
    {
     "title": "Memory Copy Utilization",
     "type": "timeseries",
     "description": "Memory utilization.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 708 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"}",
       "legendFormat": "Pod: {{exported_pod}} - Node:{{Hostname}} - GPU:{{gpu}}"
      }
     ]
    },
    {
     "title": "Frame Buffer Utilization",
     "type": "timeseries",
     "description": "Used Frame Buffer.\n\nFor high-performance computing and deep learning, framebuffers are critical for holding large datasets and intermediate values during processing, ensuring maximum throughput.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 716 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_FB_USED{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"} / (DCGM_FI_DEV_FB_USED{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"} + DCGM_FI_DEV_FB_FREE{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"})",
       "legendFormat": "Pod: {{exported_pod}} - Node:{{Hostname}} - GPU:{{gpu}}"
      }
     ]
    },
    {
     "title": "GPU XID Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 716 },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_XID_ERRORS{exported_namespace=\"$namespace\", exported_pod=\"$pod\"}",
       "legendFormat": "({{Hostname}}, GPU-{{gpu}}): {{err_code}} {{err_msg}}"
      }
     ]
    },
    {
     "title": "SM Clock",
     "type": "timeseries",
     "description": "SM clock for the device.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 724 },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_SM_CLOCK{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"}",
       "legendFormat": "Pod: {{exported_pod}} - Node: {{Hostname}} - GPU: {{gpu}}"
      }
     ]
    },
    {
     "title": "PCIe Throughput",
     "type": "timeseries",
     "description": "The number of bytes of active PCIe data including both header and payload.\n\nNote that this is from the perspective of the GPU, so copying data from host to device (HtoD) would be reflected in this metric.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 724 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "DCGM_FI_PROF_PCIE_RX_BYTES{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"}",
       "legendFormat": "RX Pod: {{exported_pod}} -  Node: {{Hostname}} - GPI: {{gpu}} - Bus ID: {{pci_bus_id}}"
      },
      {
       "expr": "DCGM_FI_PROF_PCIE_TX_BYTES{exported_namespace=\"$namespace\", exported_pod=\"$pod\"}",
       "legendFormat": "TX Pod: {{exported_pod}} -  Node: {{Hostname}} - GPI: {{gpu}} - Bus ID: {{pci_bus_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "vLLM internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Configs",
     "type": "table",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 378 },
     "targets": [
      {
       "expr": "vllm:cache_config_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Running Requests",
     "type": "barchart",
     "gridPos": { "h": 5, "w": 15, "x": 9, "y": 378 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vllm:num_requests_running{pod=~\"$pod\", namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Request Prompt Tokens (AVG)",
     "type": "timeseries",
     "description": "Histogram of input prompt token counts.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 383 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(vllm:request_prompt_tokens_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / clamp_min(rate(vllm:request_prompt_tokens_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), 1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Request Prompt Tokens (Sum)",
     "type": "timeseries",
     "description": "Histogram of input prompt token counts.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 383 },
     "targets": [
      {
       "expr": "vllm:request_prompt_tokens_sum{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Token Generations (AVG)",
     "type": "timeseries",
     "description": "Histogram of generation token counts.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 391 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(vllm:request_generation_tokens_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / clamp_min(rate(vllm:request_generation_tokens_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), 1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Token Generations (Sum)",
     "type": "timeseries",
     "description": "Histogram of generation token counts.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 391 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vllm:request_generation_tokens_sum{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Request Queue Time (AVG)",
     "type": "timeseries",
     "description": "Queue time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 399 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(vllm:request_queue_time_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / clamp_min(rate(vllm:request_queue_time_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), 1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Request Queue Time (95th Percentile)",
     "type": "timeseries",
     "description": "Queue time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 399 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(vllm:request_queue_time_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time To First Token (AVG)",
     "type": "timeseries",
     "description": "Time to first token (TTFT).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 407 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(vllm:time_to_first_token_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / clamp_min(rate(vllm:time_to_first_token_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), 1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time To First Token (95th Percentile)",
     "type": "timeseries",
     "description": "Time to first token (TTFT).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 407 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(vllm:time_to_first_token_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Inter Token Latency (AVG)",
     "type": "timeseries",
     "description": "Inter-token latency.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 415 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(vllm:inter_token_latency_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / clamp_min(rate(vllm:inter_token_latency_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), 1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Inter Token Latency (95th Percentile)",
     "type": "timeseries",
     "description": "Inter-token latency.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 415 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(vllm:inter_token_latency_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Output Token (AVG)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 423 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(vllm:request_time_per_output_token_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / clamp_min(rate(vllm:request_time_per_output_token_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), 1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Output Token (95th Percentile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 423 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(vllm:request_time_per_output_token_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "End To End Latency (AVG)",
     "type": "timeseries",
     "description": "End-to-end request latency.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 431 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(vllm:e2e_request_latency_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / clamp_min(rate(vllm:e2e_request_latency_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), 1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "End To End Latency (95th Percentile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 431 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(vllm:e2e_request_latency_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Prefill Time (AVG)",
     "type": "timeseries",
     "description": "Request prefill time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 439 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(vllm:request_prefill_time_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / clamp_min(rate(vllm:request_prefill_time_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), 1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Prefill Time (95th Percentile)",
     "type": "timeseries",
     "description": "Request prefill time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 439 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(vllm:request_prefill_time_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Decode Time (AVG)",
     "type": "timeseries",
     "description": "Request decode time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 447 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(vllm:request_decode_time_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / clamp_min(rate(vllm:request_decode_time_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), 1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Decode Time (95th Percentile)",
     "type": "timeseries",
     "description": "Request decode time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 447 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(vllm:request_decode_time_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "KV Cache Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 455 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "vllm:kv_cache_usage_perc{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Prefix Cache Hits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 455 },
     "targets": [
      {
       "expr": "vllm:prefix_cache_hits_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Request Success Total Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 463 },
     "targets": [
      {
       "expr": "vllm:request_success_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "Pod: {{pod}} Reason: {{finished_reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LMCache internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time To Store (AVG)",
     "type": "timeseries",
     "description": "Time taken to store to the cache (seconds).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(lmcache:time_to_store_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / clamp_min(rate(lmcache:time_to_store_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), 1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time To Store (95th Percentile)",
     "type": "timeseries",
     "description": "Time taken to store to the cache (seconds).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(lmcache:time_to_store_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time to Retrieve (AVG)",
     "type": "timeseries",
     "description": "Time taken to retrieve from the cache (seconds).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(lmcache:time_to_retrieve_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / clamp_min(rate(lmcache:time_to_retrieve_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), 1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time to Retrieve (95th Percentile)",
     "type": "timeseries",
     "description": "Time taken to retrieve from the cache (seconds).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(lmcache:time_to_retrieve_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Store Speed (AVG)",
     "type": "timeseries",
     "description": "Storage speed (tokens per second).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(lmcache:store_speed_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / clamp_min(rate(lmcache:store_speed_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), 1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Retrieve Speed (AVG)",
     "type": "timeseries",
     "description": "Retrieval speed (tokens per second).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(lmcache:retrieve_speed_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / clamp_min(rate(lmcache:retrieve_speed_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), 1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Num Hit Tokens (in vLLM)",
     "type": "timeseries",
     "description": "Number of hit tokens in vLLM.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lmcache:num_vllm_hit_tokens_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Num Stored Tokens",
     "type": "timeseries",
     "description": "Total number of tokens stored in LMCache.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lmcache:num_stored_tokens_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Num Requested Tokens",
     "type": "timeseries",
     "description": "Total number of tokens requested for retrieval.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lmcache:num_requested_tokens_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}: total"
      },
      {
       "expr": "lmcache:num_hit_tokens_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}: hit"
      }
     ]
    },
    {
     "title": "Num Lookup Tokens",
     "type": "timeseries",
     "description": "Total number of tokens requested in lookup operations.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lmcache:num_lookup_tokens_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}: total"
      },
      {
       "expr": "lmcache:num_lookup_hits_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}: hit"
      }
     ]
    }
   ]
  }
 ]
}