## NOTE: This file is template for model values configuration.
## Please create a copy of this file and fill in the values accordingly.

# namespace configs
namespace: llm-servings
image:
  tag: v0.15.0

# model configs
# NOTES:
# - replace all `placeholder` parts
# - uncomment max-model-len if it's needed
configs:
  name: name-placeholder
  model: model-placeholder
  gpu_memory_utilization: 0.9
  kv_transfer_config: '{"kv_connector":"LMCacheConnectorV1", "kv_role":"kv_both"}'
  # kv_transfer_config: '{"kv_connector":"MultiConnector", "kv_role":"kv_both", "kv_connector_extra_config": {"connectors": [{"kv_connector": "OffloadingConnector", "kv_role": "kv_both", "kv_connector_extra_config": {"cpu_bytes_to_use": 10737418240}}, {"kv_connector":"LMCacheConnectorV1", "kv_role":"kv_both"}]}}'
  # max_model_len: 1000
  # max_num_seqs: 1
  lmcache:
    enable: true
    cache_type: "local_storage"
    cache_delay: 0 # 500 or 1000 ms (only on iBM2)
    chunk_size: 16
    min_retrieve_tokens: 0
    save_unfull_chunk: false
    save_decode_cache: false
    cpu:
      enable: false
      max_size: 10.0
  
# resource configs
resources:
  cpu_limit: "10"
  cpu_request: "5"
  memory_limit: "25G"
  memory_request: "12G"

# gpu configs
# RTX A5000 with 24.5 GB of VRAM (1) / Quadro 6000 with 24.5 GB of VRAM (2)
gpu:
  type: "q6000" # must be a5000 or q6000
  count: 1   # adjust this based on tensor-parallel-size you want

# storage configs
storage:
  type: "local" # must be local or gpfs

# bedrock configs
bedrock:
  enable: false
  image: ghcr.io/amirhnajafiz/bedrock-tracer:v0.0.6-beta

# Kubernetes liveness and readiness probes
liveprobe:
  initdelay: 60
  period: 60
readyprobe:
  initdelay: 60
  period: 60
